// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn0sn7uiwlFC2rIJ8FuQZj-m3Je7200Z0',
    appId: '1:476007364424:web:e44da0d0e43b597792657d',
    messagingSenderId: '476007364424',
    projectId: 'bumble-clone-project',
    authDomain: 'bumble-clone-project.firebaseapp.com',
    storageBucket: 'bumble-clone-project.firebasestorage.app',
    measurementId: 'G-BLFCPM8L3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCi1o--gMVBgS81Di1WHxbbV1-kWRh8Jw',
    appId: '1:476007364424:android:d2ba5299dc8caf9492657d',
    messagingSenderId: '476007364424',
    projectId: 'bumble-clone-project',
    storageBucket: 'bumble-clone-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvzT5mSJ4ys49SVVQFyJYXPGZtzVjZPP4',
    appId: '1:476007364424:ios:c653843037ac1d2192657d',
    messagingSenderId: '476007364424',
    projectId: 'bumble-clone-project',
    storageBucket: 'bumble-clone-project.firebasestorage.app',
    iosBundleId: 'com.example.bumble',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvzT5mSJ4ys49SVVQFyJYXPGZtzVjZPP4',
    appId: '1:476007364424:ios:c653843037ac1d2192657d',
    messagingSenderId: '476007364424',
    projectId: 'bumble-clone-project',
    storageBucket: 'bumble-clone-project.firebasestorage.app',
    iosBundleId: 'com.example.bumble',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn0sn7uiwlFC2rIJ8FuQZj-m3Je7200Z0',
    appId: '1:476007364424:web:ee50aac491f2a6ec92657d',
    messagingSenderId: '476007364424',
    projectId: 'bumble-clone-project',
    authDomain: 'bumble-clone-project.firebaseapp.com',
    storageBucket: 'bumble-clone-project.firebasestorage.app',
    measurementId: 'G-S1D5SG4W6T',
  );
}
